// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNGqMXkv5aG8GAYD6DHGdj3VD6SIo6i88',
    appId: '1:1025198753021:web:d9c276cca8af61c7376a94',
    messagingSenderId: '1025198753021',
    projectId: 'book-app-2d34b',
    authDomain: 'book-app-2d34b.firebaseapp.com',
    storageBucket: 'book-app-2d34b.firebasestorage.app',
    measurementId: 'G-W6MW81WC9G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-eyv5o1EXeEeF_t8-EzEaEkQhUI90ks8',
    appId: '1:1025198753021:android:3c24aa82cae0e44a376a94',
    messagingSenderId: '1025198753021',
    projectId: 'book-app-2d34b',
    storageBucket: 'book-app-2d34b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeNAkKo6gomsSFxbj_E2f48gX42CtZfEA',
    appId: '1:1025198753021:ios:190617516af8a84d376a94',
    messagingSenderId: '1025198753021',
    projectId: 'book-app-2d34b',
    storageBucket: 'book-app-2d34b.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeNAkKo6gomsSFxbj_E2f48gX42CtZfEA',
    appId: '1:1025198753021:ios:190617516af8a84d376a94',
    messagingSenderId: '1025198753021',
    projectId: 'book-app-2d34b',
    storageBucket: 'book-app-2d34b.firebasestorage.app',
    iosBundleId: 'com.example.bookApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNGqMXkv5aG8GAYD6DHGdj3VD6SIo6i88',
    appId: '1:1025198753021:web:66d8828f2b7da935376a94',
    messagingSenderId: '1025198753021',
    projectId: 'book-app-2d34b',
    authDomain: 'book-app-2d34b.firebaseapp.com',
    storageBucket: 'book-app-2d34b.firebasestorage.app',
    measurementId: 'G-XLYVLV3MBQ',
  );
}
